#delay와 period의 단위는 tick 단위입니다. ex: 20 = 1초, 1200 = 60초(1분)

#delay는 잠수맵 이동 후 첫번째로 지급되는 포인트를 몇 초 혹은 몇 분 뒤에 지급할 것인지 설정할 수 있는 변수입니다.
delay: 200

#period는 첫번째로 지급되는 포인트 이후 몇 초 혹은 몇 분 간격으로 포인트를 지급할 것인지 설정할 수 있는 변수입니다.
period: 200

#value는 설정한 시간 뒤에 플레이어에게 지급할 잠수포인트의 값입니다.
value: 500

#/잠수 명령어를 통해 잠수맵으로 이동하였을 때 화면에 나타나는 Title 입니다.
#마인크래프트 색코드를 사용하실 수 있습니다. (&a, &e, &l ...)
title: ""

#/잠수 명령어를 통해 잠수맵으로 이동하였을 때 화면에 나타나는 SubTitle 입니다.
#마인크래프트 색코드를 사용하실 수 있습니다. (&a, &e, &l ...)
subtitle: ""

#Title이 fade-in 되는 시간. 단위: ms(밀리세컨드)
fadeIn: 500

#Title이 지속되는 시간. 단위: ms(밀리세컨드)
stay: 3000

#Title이 fade-out 되는 시간. 단위: ms(밀리세컨드)
fadeOut: 500