#delay와 period의 단위는 tick 단위입니다. ex: 20 = 1초, 1200 = 60초(1분)

#delay는 잠수맵 이동 후 첫번째로 지급되는 포인트를 몇 초 혹은 몇 분 뒤에 지급할 것인지 설정할 수 있는 변수입니다.
delay:

#period는 첫번째로 지급되는 포인트 이후 몇 초 혹은 몇 분 간격으로 포인트를 지급할 것인지 설정할 수 있는 변수입니다.
period:

#value는 설정한 시간 뒤에 플레이어에게 지급할 잠수포인트의 값입니다.
value: