name: AFKPlugin
version: '${project.version}'
main: net.teamuni.afkplugin.AFKPlugin
api-version: 1.18
depend: [Multiverse-Core]
commands:
  잠수:
    permission: afk.afk
    aliases: [afk]
  잠수지역설정:
    permission: afk.setpoint
  afkplugin:
    permission: afk.reload
  잠수포인트:
    permission: afk.afk
permissions:
  afk.afk:
    default: true
  afk.setpoint:
    default: op
  afk.reload:
    default: op