name: AFKPlugin
version: '${project.version}'
main: net.teamuni.afkplugin.AFKPlugin
api-version: 1.18
commands:
  잠수:
    permission: afk.afk
  잠수지역설정:
    permission: afk.setpoint
  afkplugin:
    permission: afk.reload

permissions:
  afk.afk:
    default: true
  afk.setpoint:
    default: op
  afk.reload:
    default: op